In [53]:
import pandas as pd
from sklearn.impute import SimpleImputer
import seaborn as sns
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import numpy as np

In [54]:
data = pd.read_csv("listings.csv")
data

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,183319,https://www.airbnb.com/rooms/183319,20220909140055,2022-09-10,previous scrape,Panoramic Ocean View Venice Beach,Craftsmen style penthouse with ocean view from...,About as close to the beach as you can live in...,https://a0.muscache.com/pictures/1170205/e2596...,867995,...,5.00,5.00,5.00,NaN,f,2,2,0,0,0.02
1,51307,https://www.airbnb.com/rooms/51307,20220909140055,2022-09-10,city scrape,Spanish Bungalow Guest House LA CA. 30 plus ni...,PRIVATE GUEST HOUSE<br /><br /><b>The space</b...,"Local LA Community , shops and restaurants in...",https://a0.muscache.com/pictures/294658/ac8d6e...,235568,...,4.85,4.95,4.76,NaN,f,2,2,0,0,0.98
2,184314,https://www.airbnb.com/rooms/184314,20220909140055,2022-09-10,previous scrape,Boho Chic Flat..Steps to Beach!,"Bright, airy, quiet 1 bdr located just steps f...",You are in one of the beach locations in Los A...,https://a0.muscache.com/pictures/0bc2f8b7-9378...,884031,...,4.93,4.89,4.85,NaN,t,1,1,0,0,0.22
3,51498,https://www.airbnb.com/rooms/51498,20220909140055,2022-09-10,city scrape,Guest House With Its Own Entrance/Exit and Hot...,"Fully self-contained, separate structure, with...",We are close to Venice without the hassle of n...,https://a0.muscache.com/pictures/83426633/c9e3...,236758,...,4.90,4.83,4.74,HSR19-001336,f,1,1,0,0,2.60
4,109,https://www.airbnb.com/rooms/109,20220909140055,2022-09-10,city scrape,Amazing bright elegant condo park front *UPGRA...,"*** Unit upgraded with new bamboo flooring, br...",NaN,https://a0.muscache.com/pictures/4321499/1da98...,521,...,4.00,5.00,4.00,NaN,f,1,1,0,0,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45810,26665862,https://www.airbnb.com/rooms/26665862,20220909140055,2022-09-10,previous scrape,"Queen Bed, Foam Mattress",Queen bed with a soft foam mattress in a priva...,"-Near Fairview Regional Park with hiking, biki...",https://a0.muscache.com/pictures/2b23e74c-89da...,82712887,...,4.94,4.88,4.83,NaN,f,2,0,2,0,2.15
45811,26898605,https://www.airbnb.com/rooms/26898605,20220909140055,2022-09-10,previous scrape,*SANITIZED* Modern Zen Getaway | Relax & Reple...,Are you more than ready for a Local Getaway?<b...,We are conveniently located just minutes from ...,https://a0.muscache.com/pictures/miso/Hosting-...,202090530,...,4.89,4.89,4.79,NaN,f,4,4,0,0,2.83
45812,26895703,https://www.airbnb.com/rooms/26895703,20220909140055,2022-09-10,previous scrape,"Simple, Clean, Modern One Bedroom Apartment",Welcome to Anaheim! This one bedroom suite ha...,We are in a safe and happy area. The street m...,https://a0.muscache.com/pictures/c6916de2-84f8...,47063020,...,4.89,4.65,4.69,Exempt,t,12,12,0,0,4.13
45813,26954426,https://www.airbnb.com/rooms/26954426,20220909140055,2022-09-10,previous scrape,Oak Park House,"Good location, new carpet, kitchen and floorin...","Close to Brookside elementary, Medea creek and...",https://a0.muscache.com/pictures/7d35579e-9e8b...,43312170,...,5.00,5.00,5.00,NaN,f,1,1,0,0,0.04
45814,27901174,https://www.airbnb.com/rooms/27901174,20220909140055,2022-09-10,previous scrape,*SANITIZED* Forest Zen| KingBD | Updated & Sty...,Now is a great time for meaningful travel with...,We are conveniently located just minutes from ...,https://a0.muscache.com/pictures/29c6bcd9-d1d4...,202090530,...,4.90,4.89,4.73,NaN,f,4,4,0,0,3.58

In [55]:
data.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

<h2>Filtering out listings from City of LA

In [56]:
data['neighbourhood_group_cleansed'].unique()

array(['City of Los Angeles', 'Other Cities', 'Unincorporated Areas', nan],
      dtype=object)

In [57]:
data = data[data['neighbourhood_group_cleansed'] == 'City of Los Angeles']
data

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,183319,https://www.airbnb.com/rooms/183319,20220909140055,2022-09-10,previous scrape,Panoramic Ocean View Venice Beach,Craftsmen style penthouse with ocean view from...,About as close to the beach as you can live in...,https://a0.muscache.com/pictures/1170205/e2596...,867995,...,5.00,5.00,5.00,NaN,f,2,2,0,0,0.02
1,51307,https://www.airbnb.com/rooms/51307,20220909140055,2022-09-10,city scrape,Spanish Bungalow Guest House LA CA. 30 plus ni...,PRIVATE GUEST HOUSE<br /><br /><b>The space</b...,"Local LA Community , shops and restaurants in...",https://a0.muscache.com/pictures/294658/ac8d6e...,235568,...,4.85,4.95,4.76,NaN,f,2,2,0,0,0.98
2,184314,https://www.airbnb.com/rooms/184314,20220909140055,2022-09-10,previous scrape,Boho Chic Flat..Steps to Beach!,"Bright, airy, quiet 1 bdr located just steps f...",You are in one of the beach locations in Los A...,https://a0.muscache.com/pictures/0bc2f8b7-9378...,884031,...,4.93,4.89,4.85,NaN,t,1,1,0,0,0.22
3,51498,https://www.airbnb.com/rooms/51498,20220909140055,2022-09-10,city scrape,Guest House With Its Own Entrance/Exit and Hot...,"Fully self-contained, separate structure, with...",We are close to Venice without the hassle of n...,https://a0.muscache.com/pictures/83426633/c9e3...,236758,...,4.90,4.83,4.74,HSR19-001336,f,1,1,0,0,2.60
5,185536,https://www.airbnb.com/rooms/185536,20220909140055,2022-09-09,city scrape,Lovely Private rm in Home to FEMALE (Red Room),"<b>The space</b><br />Hello,, Ladies!!! I offe...",NaN,https://a0.muscache.com/pictures/1773782/b2ea4...,890778,...,4.85,4.77,4.38,NaN,f,2,0,2,0,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44539,52124367,https://www.airbnb.com/rooms/52124367,20220909140055,2022-09-10,city scrape,Magnificent Beach Penthouse,"Grand 2,600 square foot dog friendly contempor...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,21942371,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
44863,47218464,https://www.airbnb.com/rooms/47218464,20220909140055,2022-09-10,city scrape,House overlooking the Marina with stunning views!,Beautiful beach house located at the Del Rey L...,The Ballona Creek Bridge will take you directl...,https://a0.muscache.com/pictures/5beacc7a-d6c1...,218130018,...,5.00,5.00,4.00,NaN,f,1,0,1,0,0.05
44928,611644219965521388,https://www.airbnb.com/rooms/611644219965521388,20220909140055,2022-09-10,city scrape,Cute Beach house w/patio steps to beach.,Perfect location steps to the beach and board ...,Venice beach<br />Venice boardwalk<br />Abbott...,https://a0.muscache.com/pictures/84d396b7-3bf9...,31484173,...,4.97,4.93,4.90,NaN,f,2,2,0,0,7.13
45078,663998246296163023,https://www.airbnb.com/rooms/663998246296163023,20220909140055,2022-09-10,city scrape,Cute Venice Beach house (B),Steps to the beach. 2 blocks to Abbott Kinney....,Venice beach <br />Venice boardwalk<br />Abbot...,https://a0.muscache.com/pictures/0352f051-a65c...,31484173,...,4.85,4.92,4.92,NaN,t,2,2,0,0,6.72
45532,50877518,https://www.airbnb.com/rooms/50877518,20220909140055,2022-09-10,previous scrape,Cali Beach-Boho Studio- Just Steps from the Beach,California beach living! Located on the Marina...,NaN,https://a0.muscache.com/pictures/48001ecf-ceb6...,8366077,...,4.86,5.00,4.57,NaN,f,9,9,0,0,0.55

<h2>Dropping descriptive columns

In [58]:
data = data.drop(['id', 'listing_url',  'scrape_id', 'last_scraped', 'source', 'name', 'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about','host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood','host_has_profile_pic','neighbourhood_cleansed','property_type', 'first_review', 'last_review'], axis = 1)

In [59]:
data

,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_verifications,host_identity_verified,neighbourhood,neighbourhood_group_cleansed,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,within a day,100%,100%,f,2.0,3.0,"['email', 'phone']",f,"Los Angeles, California, United States",City of Los Angeles,...,5.00,5.00,5.00,NaN,f,2,2,0,0,0.02
1,NaN,NaN,NaN,f,2.0,2.0,"['email', 'phone']",t,"Los Angeles, California, United States",City of Los Angeles,...,4.85,4.95,4.76,NaN,f,2,2,0,0,0.98
2,NaN,NaN,NaN,f,2.0,2.0,"['email', 'phone', 'work_email']",t,"Marina del Rey, California, United States",City of Los Angeles,...,4.93,4.89,4.85,NaN,t,1,1,0,0,0.22
3,within an hour,100%,88%,f,1.0,2.0,"['email', 'phone']",t,"Los Angeles, California, United States",City of Los Angeles,...,4.90,4.83,4.74,HSR19-001336,f,1,1,0,0,2.60
5,within a few hours,100%,80%,f,2.0,2.0,"['email', 'phone']",t,NaN,City of Los Angeles,...,4.85,4.77,4.38,NaN,f,2,0,2,0,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44539,within an hour,100%,100%,t,2.0,2.0,"['email', 'phone']",t,NaN,City of Los Angeles,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
44863,within an hour,100%,100%,f,1.0,4.0,"['email', 'phone']",t,"Marina del Rey, California, United States",City of Los Angeles,...,5.00,5.00,4.00,NaN,f,1,0,1,0,0.05
44928,within an hour,100%,99%,f,2.0,3.0,"['email', 'phone']",t,"Los Angeles, California, United States",City of Los Angeles,...,4.97,4.93,4.90,NaN,f,2,2,0,0,7.13
45078,within an hour,100%,99%,f,2.0,3.0,"['email', 'phone']",t,"Los Angeles, California, United States",City of Los Angeles,...,4.85,4.92,4.92,NaN,t,2,2,0,0,6.72
45532,within a few hours,100%,89%,t,10.0,18.0,"['email', 'phone']",t,NaN,City of Los Angeles,...,4.86,5.00,4.57,NaN,f,9,9,0,0,0.55

<h2>Dealing with null values</h2>
<p>drop column if more than 30% of it is null</p>

In [60]:
data.isna().sum()

host_response_time                               4984
host_response_rate                               4984
host_acceptance_rate                             4604
host_is_superhost                                  52
host_listings_count                                 2
host_total_listings_count                           2
host_verifications                                  0
host_identity_verified                              2
neighbourhood                                    7769
neighbourhood_group_cleansed                        0
latitude                                            0
longitude                                           0
room_type                                           0
accommodates                                        0
bathrooms                                       19501
bathrooms_text                                     44
bedrooms                                         2197
beds                                              452
amenities                                           0
price                                               0
minimum_nights                                      0
maximum_nights                                      0
minimum_minimum_nights                              2
maximum_minimum_nights                              2
minimum_maximum_nights                              2
maximum_maximum_nights                              2
minimum_nights_avg_ntm                              2
maximum_nights_avg_ntm                              2
calendar_updated                                19501
has_availability                                    0
availability_30                                     0
availability_60                                     0
availability_90                                     0
availability_365                                    0
calendar_last_scraped                               0
number_of_reviews                                   0
number_of_reviews_ltm                               0
number_of_reviews_l30d                              0
review_scores_rating                             5545
review_scores_accuracy                           5693
review_scores_cleanliness                        5692
review_scores_checkin                            5697
review_scores_communication                      5692
review_scores_location                           5698
review_scores_value                              5699
license                                         11741
instant_bookable                                    0
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
reviews_per_month                                5545
dtype: int64

In [61]:
for column in data.columns:
    if data[column].isna().sum() >= len(data[column])*0.3:
        print(column)

neighbourhood
bathrooms
calendar_updated
license

In [62]:
data = data.drop(['neighbourhood','bathrooms','calendar_updated','license'], axis=1)

In [63]:
data = data.reset_index()
data

,index,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_verifications,host_identity_verified,neighbourhood_group_cleansed,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,within a day,100%,100%,f,2.0,3.0,"['email', 'phone']",f,City of Los Angeles,...,5.00,5.00,5.00,5.00,f,2,2,0,0,0.02
1,1,NaN,NaN,NaN,f,2.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,4.89,4.85,4.95,4.76,f,2,2,0,0,0.98
2,2,NaN,NaN,NaN,f,2.0,2.0,"['email', 'phone', 'work_email']",t,City of Los Angeles,...,4.78,4.93,4.89,4.85,t,1,1,0,0,0.22
3,3,within an hour,100%,88%,f,1.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,4.94,4.90,4.83,4.74,f,1,1,0,0,2.60
4,5,within a few hours,100%,80%,f,2.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,4.77,4.85,4.77,4.38,f,2,0,2,0,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19496,44539,within an hour,100%,100%,t,2.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
19497,44863,within an hour,100%,100%,f,1.0,4.0,"['email', 'phone']",t,City of Los Angeles,...,5.00,5.00,5.00,4.00,f,1,0,1,0,0.05
19498,44928,within an hour,100%,99%,f,2.0,3.0,"['email', 'phone']",t,City of Los Angeles,...,4.93,4.97,4.93,4.90,f,2,2,0,0,7.13
19499,45078,within an hour,100%,99%,f,2.0,3.0,"['email', 'phone']",t,City of Los Angeles,...,4.85,4.85,4.92,4.92,t,2,2,0,0,6.72
19500,45532,within a few hours,100%,89%,t,10.0,18.0,"['email', 'phone']",t,City of Los Angeles,...,4.86,4.86,5.00,4.57,f,9,9,0,0,0.55

In [64]:
data.isna().sum()

index                                              0
host_response_time                              4984
host_response_rate                              4984
host_acceptance_rate                            4604
host_is_superhost                                 52
host_listings_count                                2
host_total_listings_count                          2
host_verifications                                 0
host_identity_verified                             2
neighbourhood_group_cleansed                       0
latitude                                           0
longitude                                          0
room_type                                          0
accommodates                                       0
bathrooms_text                                    44
bedrooms                                        2197
beds                                             452
amenities                                          0
price                                              0
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             2
maximum_minimum_nights                             2
minimum_maximum_nights                             2
maximum_maximum_nights                             2
minimum_nights_avg_ntm                             2
maximum_nights_avg_ntm                             2
has_availability                                   0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
review_scores_rating                            5545
review_scores_accuracy                          5693
review_scores_cleanliness                       5692
review_scores_checkin                           5697
review_scores_communication                     5692
review_scores_location                          5698
review_scores_value                             5699
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               5545
dtype: int64

In [65]:
data.price = data.price.map(lambda x: float(x[1::].replace(',','')))

<h3>Reviews</h3>

In [66]:
rating = data['review_scores_rating'].fillna(0)
accuracy = data['review_scores_accuracy'].fillna(0)
cleanliness = data['review_scores_cleanliness'].fillna(0)
checkin = data['review_scores_checkin'].fillna(0)
communication = data['review_scores_communication'].fillna(0)
location = data['review_scores_location'].fillna(0)
value = data['review_scores_value'].fillna(0)

review = []

len(value)

19501

In [67]:
for i in range(len(data)):
    count = 0
    avg = 0
    if rating[i] != 0:
        count += 1
        avg += rating[i]
    if accuracy[i] != 0:
        count += 1
        avg += accuracy[i]
    if cleanliness[i] != 0:
        count += 1
        avg += cleanliness[i]
    if checkin[i] != 0:
        count += 1
        avg += checkin[i]
    if communication[i] != 0:
        count += 1
        avg += communication[i]
    if location[i] != 0:
        count += 1
        avg += location[i]
    if value[i] != 0:
        count += 1
        avg += value[i]
    if count == 0:
        review.append(0)
    else:
        review.append(round(avg/count, 2))
data['overall_review'] = review
data = data.drop(['review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value'], axis = 1)

In [68]:
imputer = SimpleImputer(missing_values = 0, strategy ='mean')
data['overall_review'] = imputer.fit_transform(data['overall_review'].values.reshape(-1,1))
data['beds']=data['beds'].fillna(data['beds'].median())
data['bedrooms']=data['bedrooms'].fillna(data['bedrooms'].median())
# imputer.transform(data['overall_review'])
data

,index,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_verifications,host_identity_verified,neighbourhood_group_cleansed,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,overall_review
0,0,within a day,100%,100%,f,2.0,3.0,"['email', 'phone']",f,City of Los Angeles,...,3,0,0,f,2,2,0,0,0.02,4.91000
1,1,NaN,NaN,NaN,f,2.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,138,0,0,f,2,2,0,0,0.98,4.77000
2,2,NaN,NaN,NaN,f,2.0,2.0,"['email', 'phone', 'work_email']",t,City of Los Angeles,...,30,0,0,t,1,1,0,0,0.22,4.84000
3,3,within an hour,100%,88%,f,1.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,378,41,2,f,1,1,0,0,2.60,4.82000
4,5,within a few hours,100%,80%,f,2.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,13,1,0,f,2,0,2,0,0.10,4.48000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19496,44539,within an hour,100%,100%,t,2.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,0,0,0,f,2,2,0,0,NaN,4.75739
19497,44863,within an hour,100%,100%,f,1.0,4.0,"['email', 'phone']",t,City of Los Angeles,...,1,0,0,f,1,0,1,0,0.05,4.86000
19498,44928,within an hour,100%,99%,f,2.0,3.0,"['email', 'phone']",t,City of Los Angeles,...,29,29,8,f,2,2,0,0,7.13,4.92000
19499,45078,within an hour,100%,99%,f,2.0,3.0,"['email', 'phone']",t,City of Los Angeles,...,13,13,5,t,2,2,0,0,6.72,4.87000
19500,45532,within a few hours,100%,89%,t,10.0,18.0,"['email', 'phone']",t,City of Los Angeles,...,7,6,1,f,9,9,0,0,0.55,4.77000

In [69]:
data['host_response_time'].unique()

array(['within a day', nan, 'within an hour', 'within a few hours',
       'a few days or more'], dtype=object)

<h3>Replacing amenities with its count </h3>

In [70]:
amenities = data['amenities']
amenities_count =[]
for ele in amenities:
    ele = len(ele.split(','))
    amenities_count.append(ele)
data['amenities'] = amenities_count

In [71]:
data['beds']=data['beds'].fillna(data['beds'].median())
data['bedrooms']=data['bedrooms'].fillna(data['bedrooms'].median())

<h3>Dropped bathroom text later</h3>

In [72]:
data['bathrooms_text'].unique()

array(['1 bath', '1 shared bath', '2.5 baths', '1 private bath',
       '1.5 baths', '2 baths', '3 baths', nan, '2 shared baths',
       '1.5 shared baths', '11 shared baths', '4 baths', '8 shared baths',
       '8 baths', '0 shared baths', '8.5 shared baths', '3.5 baths',
       '3.5 shared baths', '5 baths', '0 baths', '4.5 baths',
       '2.5 shared baths', '3 shared baths', '11.5 shared baths',
       '6.5 baths', '4.5 shared baths', 'Shared half-bath', '8.5 baths',
       '7.5 baths', 'Half-bath', '5.5 baths', '5 shared baths', '6 baths',
       '7 baths', '9 baths', '4 shared baths', '12.5 baths', '9.5 baths',
       '10 baths', 'Private half-bath', '11.5 baths', '13 baths',
       '11 baths', '13.5 baths', '25 baths', '12 baths', '10.5 baths',
       '21 baths', '15 baths'], dtype=object)

In [73]:
b = []

btest = data[data['bathrooms_text'].notna()]
btest.reset_index()

,level_0,index,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_verifications,host_identity_verified,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,overall_review
0,0,0,within a day,100%,100%,f,2.0,3.0,"['email', 'phone']",f,...,3,0,0,f,2,2,0,0,0.02,4.91000
1,1,1,NaN,NaN,NaN,f,2.0,2.0,"['email', 'phone']",t,...,138,0,0,f,2,2,0,0,0.98,4.77000
2,2,2,NaN,NaN,NaN,f,2.0,2.0,"['email', 'phone', 'work_email']",t,...,30,0,0,t,1,1,0,0,0.22,4.84000
3,3,3,within an hour,100%,88%,f,1.0,2.0,"['email', 'phone']",t,...,378,41,2,f,1,1,0,0,2.60,4.82000
4,4,5,within a few hours,100%,80%,f,2.0,2.0,"['email', 'phone']",t,...,13,1,0,f,2,0,2,0,0.10,4.48000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19452,19496,44539,within an hour,100%,100%,t,2.0,2.0,"['email', 'phone']",t,...,0,0,0,f,2,2,0,0,NaN,4.75739
19453,19497,44863,within an hour,100%,100%,f,1.0,4.0,"['email', 'phone']",t,...,1,0,0,f,1,0,1,0,0.05,4.86000
19454,19498,44928,within an hour,100%,99%,f,2.0,3.0,"['email', 'phone']",t,...,29,29,8,f,2,2,0,0,7.13,4.92000
19455,19499,45078,within an hour,100%,99%,f,2.0,3.0,"['email', 'phone']",t,...,13,13,5,t,2,2,0,0,6.72,4.87000
19456,19500,45532,within a few hours,100%,89%,t,10.0,18.0,"['email', 'phone']",t,...,7,6,1,f,9,9,0,0,0.55,4.77000

In [74]:

# # data['bathrooms_text'].values[5555].split()
# for ele in btest['bathrooms_text'].values:
#     if ele.strip() == 'Private' or ele.strip() == 'Shared half-bath' or ele.strip() == 'Half-bath' or ele.strip() == 'Shared':
#         print(ele)
#         b.append(0.5)
#     else:
# #         print(ele)
#         b.append(float(ele.split()[0]))

# len(btest)
# # btest['bathrooms_text'].unique()
# # btest['price'].corr(btest['bathrooms_text'])

In [75]:
data.corr()

,index,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,beds,amenities,price,...,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,overall_review
index,1.000000,0.141194,0.150732,0.050022,-0.033554,0.169539,0.154160,0.121508,0.145217,0.072579,...,0.340075,-0.382422,-0.068934,0.021113,0.191487,0.144564,0.138789,0.024185,0.120082,-0.076936
host_listings_count,0.141194,1.000000,0.986506,0.001694,-0.008844,-0.076023,-0.062853,-0.088869,-0.006870,-0.027558,...,0.134404,-0.087478,-0.068570,-0.069194,0.927687,0.979606,0.039333,-0.014366,-0.080097,-0.054157
host_total_listings_count,0.150732,0.986506,1.000000,-0.000985,-0.008839,-0.071102,-0.060939,-0.086331,-0.011939,-0.024724,...,0.138494,-0.091012,-0.070239,-0.070453,0.903294,0.954253,0.037083,-0.011697,-0.083228,-0.059971
latitude,0.050022,0.001694,-0.000985,1.000000,-0.250431,0.088078,0.077089,0.066704,0.096579,0.038007,...,0.048737,-0.045899,-0.017981,-0.015137,0.056192,-0.006809,0.164257,-0.071000,-0.019249,0.038055
longitude,-0.033554,-0.008844,-0.008839,-0.250431,1.000000,-0.129098,-0.144028,-0.120455,-0.125655,-0.085771,...,-0.077736,0.023014,0.015828,0.005906,-0.046699,-0.003038,-0.118725,0.079347,0.020752,-0.057739
accommodates,0.169539,-0.076023,-0.071102,0.088078,-0.129098,1.000000,0.840539,0.815458,0.254562,0.440899,...,0.135303,-0.049586,0.023470,0.050713,-0.071178,-0.061836,-0.022531,-0.095583,0.085322,0.005056
bedrooms,0.154160,-0.062853,-0.060939,0.077089,-0.144028,0.840539,1.000000,0.795976,0.220165,0.507331,...,0.113936,-0.083836,-0.002907,0.025039,-0.083701,-0.046450,-0.093186,-0.063888,0.029833,0.025752
beds,0.121508,-0.088869,-0.086331,0.066704,-0.120455,0.815458,0.795976,1.000000,0.242652,0.384538,...,0.122694,-0.046982,0.020227,0.041668,-0.083690,-0.082856,-0.015560,-0.006000,0.059531,0.011554
amenities,0.145217,-0.006870,-0.011939,0.096579,-0.125655,0.254562,0.220165,0.242652,1.000000,0.080786,...,0.181492,0.089655,0.167074,0.192437,0.062414,-0.028607,0.230974,-0.075832,0.202048,0.135469
price,0.072579,-0.027558,-0.024724,0.038007,-0.085771,0.440899,0.507331,0.384538,0.080786,1.000000,...,0.079677,-0.055958,-0.017128,-0.012567,-0.036923,-0.017560,-0.046402,-0.042404,0.001895,0.017528
minimum_nights,-0.101599,0.033228,0.028805,-0.012269,0.005423,-0.095648,-0.083320,-0.085417,-0.123547,-0.049307,...,-0.032143,-0.126917,-0.246902,-0.263828,0.037427,0.029820,0.022187,0.014868,-0.269736,-0.019022
maximum_nights,-0.172988,0.186240,0.182233,0.016548,0.002374,-0.004405,-0.032245,-0.023559,-0.060717,-0.005826,...,0.013803,-0.063386,-0.081755,-0.104394,0.211979,0.189583,0.080251,0.066853,-0.154223,-0.039719
minimum_minimum_nights,-0.072501,0.135741,0.128808,-0.018956,0.008618,-0.087684,-0.076250,-0.080190,-0.100893,-0.042611,...,-0.049859,-0.108082,-0.201583,-0.215004,0.130432,0.133183,0.014602,0.009917,-0.249612,-0.015895
maximum_minimum_nights,0.092222,0.950133,0.919988,-0.015928,-0.000570,-0.097389,-0.076823,-0.106980,-0.045346,-0.038182,...,0.106690,-0.100570,-0.111970,-0.115797,0.877227,0.952789,-0.024114,-0.015044,-0.149811,-0.049371
minimum_maximum_nights,-0.002822,-0.003583,-0.003821,-0.003500,0.000162,-0.011688,-0.010373,-0.010539,-0.003034,0.000190,...,0.009772,0.058970,0.056148,0.002366,-0.004828,-0.004308,-0.001804,-0.001910,0.096972,-0.011205
maximum_maximum_nights,-0.003890,-0.004149,-0.004423,-0.004270,0.003819,-0.013497,-0.011978,-0.012713,-0.007199,0.000188,...,0.014404,0.049899,0.048514,0.000187,-0.005620,-0.004975,-0.002417,-0.002205,0.082235,-0.015002
minimum_nights_avg_ntm,0.090640,0.950449,0.920136,-0.014645,0.000131,-0.098286,-0.077887,-0.107693,-0.046962,-0.038535,...,0.103888,-0.102094,-0.114874,-0.119017,0.877604,0.952861,-0.023366,-0.014844,-0.154666,-0.048716
maximum_nights_avg_ntm,-0.003697,-0.004105,-0.004376,-0.004172,0.002896,-0.013363,-0.011859,-0.012454,-0.006227,0.000194,...,0.013501,0.053836,0.052008,0.000805,-0.005553,-0.004926,-0.002311,-0.002183,0.088663,-0.014350
availability_30,0.306291,-0.077726,-0.070958,0.072807,-0.073141,0.206106,0.183485,0.179417,0.119561,0.146862,...,0.575103,-0.080895,-0.019227,-0.015990,0.015170,-0.078507,0.207864,0.103329,0.033603,-0.051066
availability_60,0.334349,-0.039852,-0.032997,0.068772,-0.079050,0.198966,0.176780,0.174741,0.152232,0.135175,...,0.648032,-0.069513,0.004059,0.009566,0.047160,-0.035550,0.188881,0.094748,0.055920,-0.051847
availability_90,0.345828,-0.011497,-0.004775,0.068788,-0.079306,0.188365,0.165083,0.165471,0.174617,0.122542,...,0.693018,-0.052501,0.027043,0.034456,0.070273,-0.004133,0.174388,0.087665,0.078011,-0.046669
availability_365,0.340075,0.134404,0.138494,0.048737,-0.077736,0.135303,0.113936,0.122694,0.181492,0.079677,...,1.000000,-0.035565,-0.006409,0.006114,0.197165,0.131565,0.175048,0.092291,0.035994,-0.055895
number_of_reviews,-0.382422,-0.087478,-0.091012,-0.045899,0.023014,-0.049586,-0.083836,-0.046982,0.089655,-0.055958,...,-0.035565,1.000000,0.604101,0.452565,-0.113948,-0.093054,-0.063402,-0.038542,0.662915,0.108022
number_of_reviews_ltm,-0.068934,-0.068570,-0.070239,-0.017981,0.015828,0.023470,-0.002907,0.020227,0.167074,-0.017128,...,-0.006409,0.604101,1.000000,0.803493,-0.087805,-0.070696,-0.050624,-0.034518,0.802756,0.083173
number_of_reviews_l30d,0.021113,-0.069194,-0.070453,-0.015137,0.005906,0.050713,0.025039,0.041668,0.192437,-0.012567,...,0.006114,0.452565,0.803493,1.000000,-0.088505,-0.069904,-0.053946,-0.036588,0.756326,0.088810
calculated_host_listings_count,0.191487,0.927687,0.903294,0.056192,-0.046699,-0.071178,-0.083701,-0.083690,0.062414,-0.036923,...,0.197165,-0.113948,-0.087805,-0.088505,1.000000,0.915247,0.365379,0.016429,-0.111124,-0.053035
calculated_host_listings_count_entire_homes,0.144564,0.979606,0.954253,-0.006809,-0.003038,-0.061836,-0.046450,-0.082856,-0.028607,-0.017560,...,0.131565,-0.093054,-0.070696,-0.069904,0.915247,1.000000,-0.037624,-0.026196,-0.090807,-0.060557
calculated_host_listings_count_private_rooms,0.138789,0.039333,0.037083,0.164257,-0.118725,-0.022531,-0.093186,-0.015560,0.230974,-0.046402,...,0.175048,-0.063402,-0.050624,-0.053946,0.365379,-0.037624,1.000000,-0.016354,-0.058987,0.018954
calculated_host_listings_count_shared_rooms,0.024185,-0.014366,-0.011697,-0.071000,0.079347,-0.095583,-0.063888,-0.006000,-0.075832,-0.042404,...,0.092291,-0.038542,-0.034518,-0.036588,0.016429,-0.026196,-0.016354,1.000000,-0.047309,-0.088680
reviews_per_month,0.120082,-0.080097,-0.083228,-0.019249,0.020752,0.085322,0.029833,0.059531,0.202048,0.001895,...,0.035994,0.662915,0.802756,0.756326,-0.111124,-0.090807,-0.058987,-0.047309,1.000000,0.101054
overall_review,-0.076936,-0.054157,-0.059971,0.038055,-0.057739,0.005056,0.025752,0.011554,0.135469,0.017528,...,-0.055895,0.108022,0.083173,0.088810,-0.053035,-0.060557,0.018954,-0.088680,0.101054,1.000000

<h2>Multiple regression</h2>

In [76]:
data1 = data.copy()
room = pd.get_dummies(data1['room_type'], prefix='room_type')
room
data1['room_type_Entire home/apt'] = room['room_type_Entire home/apt']
data1['room_type_Hotel room'] = room['room_type_Hotel room']
data1['room_type_Private room'] = room['room_type_Private room']
data1['room_type_Shared room'] = room['room_type_Shared room']
data1 = data1.drop(['room_type'], axis = 1)
data1['instant_bookable'] = data1['instant_bookable'].map(lambda x : 0 if x == 'f' else 1)
data1

,index,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_verifications,host_identity_verified,neighbourhood_group_cleansed,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,overall_review,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room
0,0,within a day,100%,100%,f,2.0,3.0,"['email', 'phone']",f,City of Los Angeles,...,2,2,0,0,0.02,4.91000,1,0,0,0
1,1,NaN,NaN,NaN,f,2.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,2,2,0,0,0.98,4.77000,1,0,0,0
2,2,NaN,NaN,NaN,f,2.0,2.0,"['email', 'phone', 'work_email']",t,City of Los Angeles,...,1,1,0,0,0.22,4.84000,1,0,0,0
3,3,within an hour,100%,88%,f,1.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,1,1,0,0,2.60,4.82000,1,0,0,0
4,5,within a few hours,100%,80%,f,2.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,2,0,2,0,0.10,4.48000,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19496,44539,within an hour,100%,100%,t,2.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,2,2,0,0,NaN,4.75739,1,0,0,0
19497,44863,within an hour,100%,100%,f,1.0,4.0,"['email', 'phone']",t,City of Los Angeles,...,1,0,1,0,0.05,4.86000,0,0,1,0
19498,44928,within an hour,100%,99%,f,2.0,3.0,"['email', 'phone']",t,City of Los Angeles,...,2,2,0,0,7.13,4.92000,1,0,0,0
19499,45078,within an hour,100%,99%,f,2.0,3.0,"['email', 'phone']",t,City of Los Angeles,...,2,2,0,0,6.72,4.87000,1,0,0,0
19500,45532,within a few hours,100%,89%,t,10.0,18.0,"['email', 'phone']",t,City of Los Angeles,...,9,9,0,0,0.55,4.77000,1,0,0,0

In [77]:
x = data1[['longitude', 'latitude', 'accommodates', 'beds', 'bedrooms','availability_30', 'overall_review','amenities','instant_bookable','room_type_Entire home/apt', 'room_type_Hotel room', 'room_type_Private room', 'room_type_Shared room' ]]
y = data1[['price']]

In [78]:
x

,longitude,latitude,accommodates,beds,bedrooms,availability_30,overall_review,amenities,instant_bookable,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room
0,-118.476000,33.992110,2,2.0,2.0,0,4.91000,22,0,1,0,0,0
1,-118.267830,34.122060,2,1.0,1.0,0,4.77000,30,0,1,0,0,0
2,-118.463120,33.974870,1,1.0,1.0,0,4.84000,18,1,1,0,0,0
3,-118.441260,34.003890,2,1.0,1.0,13,4.82000,44,0,1,0,0,0
4,-118.423730,33.961540,1,1.0,1.0,23,4.48000,29,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19496,-118.454970,33.965840,6,3.0,2.0,0,4.75739,61,0,1,0,0,0
19497,-118.454120,33.964800,1,1.0,1.0,29,4.86000,17,0,0,0,1,0
19498,-118.476150,33.986000,4,1.0,1.0,0,4.92000,68,0,1,0,0,0
19499,-118.474617,33.985284,4,1.0,1.0,3,4.87000,66,1,1,0,0,0
19500,-118.455030,33.965390,1,1.0,1.0,5,4.77000,44,0,1,0,0,0

In [79]:
# data['beds']=data['beds'].fillna(data['beds'].median())
# data['bedrooms']=data['bedrooms'].fillna(data['bedrooms'].median())

In [80]:
x.reset_index()

,index,longitude,latitude,accommodates,beds,bedrooms,availability_30,overall_review,amenities,instant_bookable,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room
0,0,-118.476000,33.992110,2,2.0,2.0,0,4.91000,22,0,1,0,0,0
1,1,-118.267830,34.122060,2,1.0,1.0,0,4.77000,30,0,1,0,0,0
2,2,-118.463120,33.974870,1,1.0,1.0,0,4.84000,18,1,1,0,0,0
3,3,-118.441260,34.003890,2,1.0,1.0,13,4.82000,44,0,1,0,0,0
4,4,-118.423730,33.961540,1,1.0,1.0,23,4.48000,29,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19496,19496,-118.454970,33.965840,6,3.0,2.0,0,4.75739,61,0,1,0,0,0
19497,19497,-118.454120,33.964800,1,1.0,1.0,29,4.86000,17,0,0,0,1,0
19498,19498,-118.476150,33.986000,4,1.0,1.0,0,4.92000,68,0,1,0,0,0
19499,19499,-118.474617,33.985284,4,1.0,1.0,3,4.87000,66,1,1,0,0,0
19500,19500,-118.455030,33.965390,1,1.0,1.0,5,4.77000,44,0,1,0,0,0

<h3>Using sklearn</h3>

In [81]:


X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
reg = LinearRegression().fit(X_train, y_train)
reg.get_params()
reg.score(x,y)
y_predict = reg.predict(X_test)
print(r2_score(y_test, y_predict))

0.25886400189836856

<h3>Using statsmodel</h3>

In [82]:
X_train = sm.add_constant(X_train)
LR = sm.OLS(y_train,X_train).fit()
LR.summary()

D:\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.275
Model:                            OLS   Adj. R-squared:                  0.274
Method:                 Least Squares   F-statistic:                     431.3
Date:                Wed, 09 Nov 2022   Prob (F-statistic):               0.00
Time:                        13:38:35   Log-Likelihood:            -1.0542e+05
No. Observations:               13650   AIC:                         2.109e+05
Df Residuals:                   13637   BIC:                         2.110e+05
Df Model:                          12
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                     -9495.4557   4859.437     -1.954      0.051    -1.9e+04      29.712
longitude                  -111.4437     52.315     -2.130      0.033    -213.989      -8.898
latitude                    -29.7897     66.510     -0.448      0.654    -160.159     100.580
accommodates                 31.4263      3.648      8.615      0.000      24.276      38.576
beds                        -36.0577      5.649     -6.384      0.000     -47.130     -24.986
bedrooms                    249.9305      7.780     32.125      0.000     234.681     265.180
availability_30               2.9168      0.395      7.384      0.000       2.143       3.691
overall_review               25.2072     13.258      1.901      0.057      -0.781      51.195
amenities                    -1.6023      0.321     -4.984      0.000      -2.232      -0.972
instant_bookable            -36.4948     10.076     -3.622      0.000     -56.246     -16.744
room_type_Entire home/apt -2969.8560   1214.803     -2.445      0.015   -5351.038    -588.674
room_type_Hotel room       -604.5001   1220.318     -0.495      0.620   -2996.491    1787.491
room_type_Private room    -2950.4794   1215.805     -2.427      0.015   -5333.625    -567.334
room_type_Shared room     -2970.6201   1214.254     -2.446      0.014   -5350.726    -590.514
==============================================================================
Omnibus:                    26135.497   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         84458952.244
Skew:                          14.714   Prob(JB):                         0.00
Kurtosis:                     387.231   Cond. No.                     1.53e+18
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.59e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [ ]:
<h2>Multiple Regression with

In [85]:
data2 = data[data['room_type'] != 'Hotel room']
room2 = pd.get_dummies(data2['room_type'], prefix='room_type')
data2['room_type_Entire home/apt'] = room2['room_type_Entire home/apt']
data2['room_type_Private room'] = room2['room_type_Private room']
data2['room_type_Shared room'] = room2['room_type_Shared room']
data2 = data2.drop(['room_type'], axis = 1)
data2['instant_bookable'] = data2['instant_bookable'].map(lambda x : 0 if x == 'f' else 1)
data2['price'] = data2['price'].map(lambda x : np.log(x))
data2

C:\Users\tejas\AppData\Local\Temp/ipykernel_21204/4058554076.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['room_type_Entire home/apt'] = room2['room_type_Entire home/apt']
C:\Users\tejas\AppData\Local\Temp/ipykernel_21204/4058554076.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['room_type_Private room'] = room2['room_type_Private room']
C:\Users\tejas\AppData\Local\Temp/ipykernel_21204/4058554076.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['room_type_Shared room'] = room2['room_type_Shared room']

,index,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_verifications,host_identity_verified,neighbourhood_group_cleansed,...,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,overall_review,room_type_Entire home/apt,room_type_Private room,room_type_Shared room
0,0,within a day,100%,100%,f,2.0,3.0,"['email', 'phone']",f,City of Los Angeles,...,0,2,2,0,0,0.02,4.91000,1,0,0
1,1,NaN,NaN,NaN,f,2.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,0,2,2,0,0,0.98,4.77000,1,0,0
2,2,NaN,NaN,NaN,f,2.0,2.0,"['email', 'phone', 'work_email']",t,City of Los Angeles,...,1,1,1,0,0,0.22,4.84000,1,0,0
3,3,within an hour,100%,88%,f,1.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,0,1,1,0,0,2.60,4.82000,1,0,0
4,5,within a few hours,100%,80%,f,2.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,0,2,0,2,0,0.10,4.48000,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19496,44539,within an hour,100%,100%,t,2.0,2.0,"['email', 'phone']",t,City of Los Angeles,...,0,2,2,0,0,NaN,4.75739,1,0,0
19497,44863,within an hour,100%,100%,f,1.0,4.0,"['email', 'phone']",t,City of Los Angeles,...,0,1,0,1,0,0.05,4.86000,0,1,0
19498,44928,within an hour,100%,99%,f,2.0,3.0,"['email', 'phone']",t,City of Los Angeles,...,0,2,2,0,0,7.13,4.92000,1,0,0
19499,45078,within an hour,100%,99%,f,2.0,3.0,"['email', 'phone']",t,City of Los Angeles,...,1,2,2,0,0,6.72,4.87000,1,0,0
19500,45532,within a few hours,100%,89%,t,10.0,18.0,"['email', 'phone']",t,City of Los Angeles,...,0,9,9,0,0,0.55,4.77000,1,0,0

In [86]:
x2 = data2[['longitude', 'latitude', 'accommodates', 'beds', 'bedrooms','availability_30', 'overall_review','amenities','instant_bookable','room_type_Entire home/apt', 'room_type_Private room', 'room_type_Shared room' ]]
y2 = data2[['price']]

In [87]:
X2_train, X2_test, y2_train, y2_test = train_test_split(x2, y2, test_size=0.3, random_state=42)
reg2 = LinearRegression().fit(X2_train, y2_train)
reg2.get_params()
reg2.score(x2,y2)
y2_predict = reg2.predict(X2_test)
print(r2_score(y2_test, y2_predict))

0.6294829846425377

In [90]:
x2_ols = sm.add_constant(x2)
LR2 = sm.OLS(y2,x2_ols).fit()
LR2.summary()

D:\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.622
Model:                            OLS   Adj. R-squared:                  0.622
Method:                 Least Squares   F-statistic:                     2914.
Date:                Wed, 09 Nov 2022   Prob (F-statistic):               0.00
Time:                        13:42:48   Log-Likelihood:                -16391.
No. Observations:               19474   AIC:                         3.281e+04
Df Residuals:                   19462   BIC:                         3.290e+04
Df Model:                          11
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                       -32.6890      3.920     -8.340      0.000     -40.372     -25.006
longitude                    -0.5356      0.045    -11.923      0.000      -0.624      -0.448
latitude                     -0.4900      0.057     -8.605      0.000      -0.602      -0.378
accommodates                  0.0908      0.003     28.278      0.000       0.085       0.097
beds                         -0.0650      0.005    -13.058      0.000      -0.075      -0.055
bedrooms                      0.3481      0.007     51.046      0.000       0.335       0.361
availability_30               0.0071      0.000     20.893      0.000       0.006       0.008
overall_review                0.1270      0.012     10.970      0.000       0.104       0.150
amenities                     0.0025      0.000      9.007      0.000       0.002       0.003
instant_bookable             -0.0673      0.009     -7.785      0.000      -0.084      -0.050
room_type_Entire home/apt   -10.3651      1.307     -7.933      0.000     -12.926      -7.804
room_type_Private room      -10.8289      1.307     -8.282      0.000     -13.392      -8.266
room_type_Shared room       -11.4949      1.306     -8.803      0.000     -14.055      -8.935
==============================================================================
Omnibus:                     4499.394   Durbin-Watson:                   1.937
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            41327.172
Skew:                           0.850   Prob(JB):                         0.00
Kurtosis:                       9.931   Cond. No.                     5.92e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.11e-28. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [47]:
y2_train

        price
8632    290.0
19078   711.0
18975   109.0
3154   1107.0
8331     74.0
...       ...
11284    69.0
11964   233.0
5390    161.0
860      80.0
15795   208.0

[13650 rows x 1 columns]

In [89]:
X2_train

,const,longitude,latitude,accommodates,beds,bedrooms,availability_30,overall_review,amenities,instant_bookable,room_type_Entire home/apt,room_type_Private room,room_type_Shared room
6079,1.0,-118.36207,34.07308,3,1.0,1.0,0,4.90000,17,0,1,0,0
965,1.0,-118.36548,34.07012,1,1.0,1.0,0,4.75739,5,0,0,1,0
8308,1.0,-118.17772,34.07369,8,4.0,4.0,0,4.86000,20,0,1,0,0
1662,1.0,-118.46563,33.99697,2,1.0,1.0,0,4.95000,22,0,1,0,0
455,1.0,-118.46441,34.04233,4,2.0,2.0,2,4.89000,45,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11310,1.0,-118.20348,34.11668,2,2.0,2.0,7,4.59000,24,1,1,0,0
11990,1.0,-118.25952,34.05733,4,2.0,2.0,30,4.86000,22,0,1,0,0
5392,1.0,-118.41395,34.09559,2,1.0,1.0,0,4.75739,25,0,0,1,0
860,1.0,-118.31308,34.01960,3,2.0,3.0,0,4.93000,15,0,1,0,0
15822,1.0,-118.42768,33.98863,6,3.0,3.0,0,4.75739,53,0,1,0,0